### PR TITLE
DIRMINA-1124 : make NioProcessor and NioSocketAcceptor extendable by removing final from class declaration

### PR DESCRIPTION
**Pull request by snufkinsnorka**

### CODE REVIEW

**Comment by elecharny** [comment]
Wondering: why would you make those classes extensible ?

**Comment by snufkinsnorka** [comment]
We want to extend those in order to add ability of moving IoSession established sockets from processor to processor. 
We use this when we want to move connections between different servers (which are implemented with different classLoaders)

In order to implement this we need for example to override ShadowNioSocketAcceptor.open methods. 
For example, during open, we no longer need to create the socket, but we do need to register the selector, which is why we also change it to be protected.

**Comment by snufkinsnorka** [comment]
@elecharny ping :)

**Comment by elecharny** [comment]
Was thinking about your requirement...

Wondering : would it make sense for you to implement your own flavor of NioAcceptor for that purpose ? 

(note : your suggestion is trivial, and should not cause any trouble, it's just that I have trouble seeing a need to shuffle sessions. Sessions are distributed over a pool of IoPorocessor instances, and execution starts there. If you need to associate a session to a specific IoProcessor, then that means you manage those IoProcessor instances in a different way, so a pool would not necessarily be the right way to deal with sessions. I may miss something...)

**Comment by snufkinsnorka** [comment]
You are right, this is exactly our goal. It's just that the new NioAcceptor we implemented is a pretty simple extension over the existing NioSocketAcceptor (which I'm changing here to support inheritance), and it's a shame to duplicate all of the code.

A bit more context: we have long-running tcp connections, which we don't want to disconnect. When we deploy new code to our servers we start it with a new class loader, and pass the sockets from the old code to the new one. What we did is fork Mina (with the changes I'm suggesting here), so we can extend NioSocketAcceptor to support this functionality. This is working well for us, but we'd like to get rid of this fork.

**Comment by elecharny** [comment]
On 23/04/2020 10:44, Anna Kukliansky wrote:
>
> You are right, this is exactly our goal. It's just that the new 
> NioAcceptor we implemented is a pretty simple extension over the 
> existing NioSocketAcceptor (which I'm changing here to support 
> inheritance), and it's a shame to duplicate all of the code.
>
> A bit more context: we have long-running tcp connections, which we 
> don't want to disconnect. When we deploy new code to our servers we 
> start it with a new class loader, and pass the sockets from the old 
> code to the new one. What we did is fork Mina (with the changes I'm 
> suggesting here), so we can extend NioSocketAcceptor to support this 
> functionality. This is working well for us, but we'd like to get rid 
> of this fork.
>

Ah, now it makes more sense to me.


Ok, I think it's a no brainer. I may take a bit of time this week-end to 
check some other MINA patches, in order to cut a release in the coming 
days. That may take a week or two, I'm currently pretty much under the 
water with many other tasks.

**Comment by snufkinsnorka** [comment]
Thank you very much! 🙏

**Comment by jon-valliere** [comment]
Is there any way to disable issues on github and force everyone to use JIRA?

EDIT: Never-mind, guess this is a PR the email said "issue"

**Comment by elecharny** [comment]
On 23/04/2020 15:42, jon-valliere wrote:
>
> Is there any way to disable issues on github and force everyone to use 
> JIRA?
>

I don't think so.


The best is to kindly ask people to fill a JIRA pointing to the GH PR.

**Comment by jon-valliere** [comment]
Please create a enhancement request on JIRA https://issues.apache.org/jira/secure/Dashboard.jspa  This way we will have a Ticket # to assign the merge/commit then rename this PR with the Ticket # (e.g. DIRMINA-XXX)

**Comment by snufkinsnorka** [comment]
@elecharny  - any news on this pull request? Anything I can do to help merging this to the matser?

**Comment by jon-valliere** [comment]
@snufkinsnorka if you want to attach a patch diff to your JIRA ticket, I will merge to 2.1.X.  I don't know how to take pull requests from Github into the main repo.  Additionally, it will have to be merged anyway due to changes since your pull request was created.

**Comment by snufkinsnorka** [comment]
@jon-valliere  Im afraid I dont have a permission to commit to the main repo. Maybe you can provide me access for this?
Here is the jira ticket : https://issues.apache.org/jira/browse/DIRMINA-1124

**Comment by jon-valliere** [comment]
I think you misunderstood my request.  I do have permissions to modify the main repo but am  not entirely sure how to take pull requests.  In the mean time, I need you to rebase your fork on the current 2.1.X trunk then create a patch diff file and attach it to your JIRA ticket.  I will then apply the patch to the main repo.

**Comment by snufkinsnorka** [comment]
@jon-valliere I added patch file to the jira ticket

**Comment by jon-valliere** [comment]
Closing because the patch was merged into main on https://gitbox.apache.org/repos/asf?p=mina.git;a=commit;h=53d96b92d4bf14fad2b87d8fdeca4ebc5019b6d8

**Pull request closed without merging**
