### PR TITLE
Update BogusSslContextFactory.java

### PR DESCRIPTION
**Pull request by YYTVicky**

### CODE REVIEW

**Comment by YYTVicky** [comment]
Hi, 
we found the TLS is not secure for build connection (https://www.packetlabs.net/tls-1-1-no-longer-secure/), therefor our tool reports the vulnerability for this project, would you mind changing it to TLSv1.3 for security concern?

Thanks and hope to hear any feedback from you!

**Comment by jon-valliere** [comment]
The repo has already been updated to default to TLSv1.2 in all relevant places outside of the unit tests.

**Comment by mahirkabir** [comment]
Hi @jon-valliere , thanks for letting @YYTVicky know about the update. However, I was wondering if it was done in another repository. I cloned this repository and can still find "TLS" used in the code. I searched for "TLSv1.2" in the **trunk** branch and found nothing. Am I missing something? Please let me know.

Also, I would like to add that, TLSv1.3 might be a better option to use instead of TLSv1.2. For reference - https://calcomsoftware.com/leaving-tls1-2-using-tls1-3/ . 

Once again, thanks a lot for your time. If you have any questions, please feel free to let me know.

**Comment by jon-valliere** [comment]
> Hi @jon-valliere , thanks for letting @YYTVicky know about the update. However, I was wondering if it was done in another repository. I cloned this repository and can still find "TLS" used in the code. I searched for "TLSv1.2" in the **trunk** branch and found nothing. Am I missing something? Please let me know.
> 
> Also, I would like to add that, TLSv1.3 might be a better option to use instead of TLSv1.2. For reference - https://calcomsoftware.com/leaving-tls1-2-using-tls1-3/ .
> 
> Once again, thanks a lot for your time. If you have any questions, please feel free to let me know.

The trunk is 10 years old.  Checkout 2.1.X  There is nothing stopping you from using TLSv1.3 but for compatibility reasons with older versions of Java, the default will stay at TLSv1.2 until a decision is made not to support older platforms.

**Comment by mahirkabir** [comment]
Hi @jon-valliere , thanks for the clarification.

**Pull request closed without merging**
