### PR TITLE
DIRMINA-1152: IoServiceStatistics introduces huge latencies

### PR DESCRIPTION
**Pull request by dmitriinovikov**
DIRMINA-1152: IoServiceStatistics introduces huge latencies - make IoServiceStatistics calculation configurable

### CODE REVIEW

**Comment by elecharny** [comment]
Sounds very reasonable to me !

I'll review the proposal.

**Comment by dmitriinovikov** [comment]
> Sounds very reasonable to me !
> 
> I'll review the proposal.

Hi Emmanuel, 

Thanks for your attention. Did you had a chance to look at PR?

**Comment by elecharny** [comment]
Hi Dmitri;

sorry for the delay, yes, I had a quick look, but I need more time. I was quite busy this week with the  Log4Shell issue...

**Comment by dmitriinovikov** [comment]
No problem, Emmanuel. I just wanted to ensure you didn't forget about my PR.

**Comment by elecharny** [comment]
Patch applied in 2.1.X branch

**Comment by elecharny** [comment]
And applied in 2.0.X branch too.

**Pull request merged**
